// The handwritten "Expenses / online purchases, consumables" sheets,
// September 2025 to September 2026, line by line as written. Sheets
// carry no day, so every line is dated the 1st of its month. Where the
// lines do not add up to the total the sheet states, a "balance as
// written" line closes the gap so each month matches the paper.
export interface MoneyBookSeedLine {
  month: string;
  title: string;
  amount: number;
  quantity?: number;
  usd?: number;
  category: string;
}

export const MONEY_BOOK_SEED_CATEGORIES: {
  key: string;
  name: string;
  color: string;
}[] = [
  { key: "batteries", name: "Batteries & BMS", color: "#0FA53A" },
  { key: "controllers", name: "Motors & controllers", color: "#2563EB" },
  {
    key: "drivetrain",
    name: "Drivetrain (sprockets, gearboxes)",
    color: "#F59E0B",
  },
  { key: "tools", name: "Tools & equipment", color: "#7C3AED" },
  { key: "electrical", name: "Electrical parts", color: "#DC2626" },
  { key: "devices", name: "Trackers & devices", color: "#0891B2" },
  { key: "vehicle", name: "Vehicle body & tyres", color: "#78716C" },
  { key: "consumables", name: "Consumables", color: "#DB2777" },
  { key: "others", name: "Others", color: "#6B7280" },
];

export const MONEY_BOOK_SEED_ACCOUNTS = [
  "Cash",
  "Bank transfer",
  "Online payment",
];

export const MONEY_BOOK_SEED_LINES: MoneyBookSeedLine[] = [
  {
    month: "2025-09",
    title: "BMS 250Ah",
    amount: 152570,
    quantity: 1,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-09",
    title: "JK BMS 200Ah",
    amount: 260430,
    quantity: 2,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-09",
    title: "Brake block for chain hoist",
    amount: 22500,
    quantity: 1,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2025-09",
    title: "Mosfet for MPPT solar controller",
    amount: 26000,
    quantity: 40,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2025-09",
    title: "MPPT controller 120Ah",
    amount: 1888656,
    quantity: 7,
    usd: 1036,
    category: "controllers",
  },
  {
    month: "2025-09",
    title: "JK BMS 60Ah",
    amount: 305140,
    quantity: 10,
    usd: 190,
    category: "batteries",
  },
  {
    month: "2025-09",
    title: "DC fan 12V",
    amount: 370986,
    quantity: 33,
    usd: 231,
    category: "electrical",
  },
  {
    month: "2025-09",
    title: "Remaining balance of controller (70%)",
    amount: 112420,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2025-10",
    title: "Complete kits Datai motors",
    amount: 5653101.8,
    quantity: 7,
    usd: 3619,
    category: "controllers",
  },
  {
    month: "2025-10",
    title: "MPPT controller",
    amount: 1882848,
    quantity: 8,
    usd: 1264,
    category: "controllers",
  },
  {
    month: "2025-11",
    title: "230Ah grade A batteries",
    amount: 47460000,
    quantity: 20,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-11",
    title: "Chain hoist 1 ton",
    amount: 2034040,
    quantity: 2,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2025-11",
    title: "Daly BMS 250A",
    amount: 656210,
    quantity: 5,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-11",
    title: "JK BMS 200Ah",
    amount: 663173,
    quantity: 7,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-11",
    title: "Hydraulic jack for swapping",
    amount: 1645800,
    quantity: 1,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2025-11",
    title: "MPPT controller",
    amount: 1688000,
    quantity: 7,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2025-12",
    title: "Grinder dryer",
    amount: 118000,
    quantity: 1,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2025-12",
    title: "Wire extractor",
    amount: 36000,
    quantity: 1,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2025-12",
    title: "Wheel bearing tyres",
    amount: 617390,
    quantity: 25,
    usd: 419.33,
    category: "vehicle",
  },
  {
    month: "2025-12",
    title: "100Ah battery",
    amount: 33380200,
    quantity: 20,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2025-12",
    title: "Motor controller",
    amount: 1419150,
    quantity: 7,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2025-12",
    title: "12V converter",
    amount: 591364,
    quantity: 10,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2025-12",
    title: "Sprockets",
    amount: 305200,
    quantity: 20,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2025-12",
    title: "Balance as written on the sheet",
    amount: 30,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-01",
    title: "12V",
    amount: 295000,
    quantity: 5,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-01",
    title: "Electric rear kits complete",
    amount: 1189236.36,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-01",
    title: "Anderson plug 175Ah",
    amount: 109349,
    quantity: 30,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-01",
    title: "Sprockets",
    amount: 663000,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-03",
    title: "AYK hijet",
    amount: 1447500,
    quantity: 2,
    usd: 863.06,
    category: "vehicle",
  },
  {
    month: "2026-03",
    title: "Sprockets",
    amount: 1294807,
    quantity: 200,
    usd: 916.62,
    category: "drivetrain",
  },
  {
    month: "2026-03",
    title: "Complete kits 3, controller 2, electric motor 2, motor phase wire",
    amount: 3180597,
    quantity: undefined,
    usd: 2174.5,
    category: "controllers",
  },
  {
    month: "2026-03",
    title: "Balance as written on the sheet",
    amount: -500,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-04",
    title:
      "Motor wire hall sensor 15, motor controller 5, front pedal 5, gear sprockets 5, motor phase wire 5",
    amount: 1055718,
    quantity: undefined,
    usd: 749.8,
    category: "controllers",
  },
  {
    month: "2026-04",
    title: "Remote control for chain hoist",
    amount: 61800,
    quantity: 2,
    usd: undefined,
    category: "tools",
  },
  {
    month: "2026-05",
    title: "MPPT controller board",
    amount: 1100560,
    quantity: 6,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-05",
    title: "Daly BMS",
    amount: 882447,
    quantity: 7,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-05",
    title: "Sprockets",
    amount: 127483.2,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-05",
    title: "Electric motor 8kw",
    amount: 2533566,
    quantity: 7,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-06",
    title: "Charge controller",
    amount: 83000,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-06",
    title: "Gearbox cover 4 units; gears 100 pcs",
    amount: 936501,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-06",
    title: "Sprockets 60 pcs and motor controller 3 pcs",
    amount: 991149,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-06",
    title: "Sprockets",
    amount: 215109,
    quantity: 30,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-06",
    title: "Nafap class",
    amount: 110000,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-06",
    title: "Metals",
    amount: 50000,
    quantity: undefined,
    usd: undefined,
    category: "consumables",
  },
  {
    month: "2026-06",
    title: "Charge controller 6 pcs, panels, wire",
    amount: 169500,
    quantity: undefined,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-06",
    title: "DC burner",
    amount: 40527,
    quantity: undefined,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-06",
    title: "Buses glasses",
    amount: 132000,
    quantity: undefined,
    usd: undefined,
    category: "vehicle",
  },
  {
    month: "2026-06",
    title: "Battery and tyres",
    amount: 283000,
    quantity: undefined,
    usd: undefined,
    category: "vehicle",
  },
  {
    month: "2026-06",
    title: "Glass",
    amount: 90000,
    quantity: undefined,
    usd: undefined,
    category: "vehicle",
  },
  {
    month: "2026-06",
    title: "Sprockets",
    amount: 180787,
    quantity: 2,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-06",
    title: "Charge controller",
    amount: 42000,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-06",
    title: "Gearbox 2 pcs and electric motor 2 pcs",
    amount: 1032175,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-07",
    title: "MPPT controller",
    amount: 367199,
    quantity: 2,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-07",
    title: "BMS Daly 250A new",
    amount: 273871,
    quantity: 2,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-07",
    title: "BMS Daly 48V",
    amount: 96350,
    quantity: undefined,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-07",
    title: "Sprockets",
    amount: 387585,
    quantity: 30,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-07",
    title: "Anderson plug",
    amount: 125014,
    quantity: undefined,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-07",
    title: "Electric motor 8kw new kits, controller and gearbox",
    amount: 850822,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-07",
    title: "Smart lock",
    amount: 29306,
    quantity: undefined,
    usd: undefined,
    category: "devices",
  },
  {
    month: "2026-07",
    title: "MPPT controller board 100A",
    amount: 367890,
    quantity: 2,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-07",
    title: "Biometric attendance",
    amount: 42253,
    quantity: undefined,
    usd: undefined,
    category: "devices",
  },
  {
    month: "2026-07",
    title: "Painting, seats and metals",
    amount: 380000,
    quantity: undefined,
    usd: undefined,
    category: "vehicle",
  },
  {
    month: "2026-07",
    title:
      "Sprockets 30, 8kw motor 1, motor controller 1, gearbox cover 2, gearbox complete 2",
    amount: 1324310,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-07",
    title: "Balance as written on the sheet",
    amount: -50000,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-08",
    title: "Sprockets 20 pcs and controller",
    amount: 357169,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-08",
    title: "Coil 8kw 2 units and sprockets 5 units",
    amount: 445622,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-08",
    title: "JK BMS 200A",
    amount: 194355,
    quantity: 2,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-08",
    title: "DC breaker",
    amount: 360000,
    quantity: undefined,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-08",
    title: "Motor controller 8kw",
    amount: 429870,
    quantity: 2,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-08",
    title: "Tracker",
    amount: 161633,
    quantity: 10,
    usd: undefined,
    category: "devices",
  },
  {
    month: "2026-08",
    title: "Back axle cover",
    amount: 77787,
    quantity: 1,
    usd: undefined,
    category: "vehicle",
  },
  {
    month: "2026-08",
    title: "MPPT controller",
    amount: 363355,
    quantity: 2,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-08",
    title: "Sprockets 30, motor 8, controller 5, gearbox new 8 set, old 4 set",
    amount: 4964441,
    quantity: undefined,
    usd: undefined,
    category: "drivetrain",
  },
  {
    month: "2026-08",
    title: "JK BMS 200Ah",
    amount: 472141,
    quantity: 5,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-08",
    title: "Electric motor 6 pcs and sprockets 5 pcs",
    amount: 2210997,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-08",
    title: "Balance as written on the sheet",
    amount: -360000,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-09",
    title: "Anderson plug 20 pcs x 2",
    amount: 197431,
    quantity: 40,
    usd: undefined,
    category: "electrical",
  },
  {
    month: "2026-09",
    title: "Motor controller",
    amount: 416010,
    quantity: 2,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-09",
    title: "Daly BMS 250A",
    amount: 436800,
    quantity: 3,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-09",
    title: "MPPT controller board",
    amount: 714862.5,
    quantity: 4,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-09",
    title: "Daly BMS 150A",
    amount: 191858,
    quantity: 2,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-09",
    title: "Mosquito lamp",
    amount: 33216,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
  {
    month: "2026-09",
    title: "Battery cell",
    amount: 58305,
    quantity: undefined,
    usd: undefined,
    category: "batteries",
  },
  {
    month: "2026-09",
    title: "Motor controller",
    amount: 404550,
    quantity: undefined,
    usd: undefined,
    category: "controllers",
  },
  {
    month: "2026-09",
    title: "Screen",
    amount: 56986,
    quantity: 10,
    usd: undefined,
    category: "devices",
  },
  {
    month: "2026-09",
    title: "Balance as written on the sheet",
    amount: -20.5,
    quantity: undefined,
    usd: undefined,
    category: "others",
  },
];
